---
- name: Configure test server
  hosts: testserver
  become: yes
  tasks:
  - name: install python3
    vars:
      ansible_python_interpreter: /usr/bin/python
    yum:
      name: python3
      ypdate_cache: yes
      state: present
  - name: install docker
    yum:
      name: docker
      update_cache: yes
      state: present
  - name: start docker
    systemd:
      name: docker
      state: started
  - name: add user docker to sudo
    user: ssdfsd
    groups: docker

